import "./globals.css";
import Header from "./../components/header";
import Footer from "./../components/footer";
import PlanetIdil from "./../components/face-animation/index";
import { Suspense } from "react";
import Script from "next/script";

export const metadata = {
  title: "IT",
  icons: {
    icon: "/favicon.ico",
  },
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="h-auto sm:h-full bg-[#90ee90]" lang="en">
      <body suppressHydrationWarning={true}>
        <div className="flex h-screen flex-col items-center justify-between">
          <Header />
          <Suspense fallback={<Loading />}>
            <PlanetIdil />
            {children}
            <Script
              id="google-adsense"
              async
              src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8827855298710754"
              crossOrigin="anonymous"
              strategy="afterInteractive"
            />
          </Suspense>
          <Footer />
        </div>
      </body>
    </html>
  );
}

function Loading() {
  return <h2>🌀 Loading...</h2>;
}
