import './globals.css'
import Header from './../components/header';
import Footer from './../components/footer';
// import Loading from './../components/loading';
import PlanetIdil from './../components/face-animation/index';
import { Suspense } from 'react'

export const metadata = {
  title: 'IT',
  // description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html className="h-auto sm:h-full bg-[#90ee90]" lang="en">
      {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
      <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100&family=Sora:wght@400;600;700&display=swap" rel="stylesheet" /> */}
      <body suppressHydrationWarning={true}>
        <div className="flex h-screen flex-col items-center justify-between" >
          <Header />
          <Suspense fallback={<Loading />}>
            <PlanetIdil />
            {children}
          </Suspense>
          <Footer />
        </div>
      </body>
    </html>
  )
}

function Loading() {
  return <h2>🌀 Loading...</h2>;
}