import './globals.css'
import Header from './../components/header';
import Footer from './../components/footer';
import PlanetIdil from './../components/face-animation/index';
import { Suspense } from 'react'

export const metadata = {
  title: 'IT',
  // description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html className="h-auto sm:h-full bg-[#90ee90]" lang="en">
      <body suppressHydrationWarning={true}>
        <div className="flex h-screen flex-col items-center justify-between" >
          <Header />
          <Suspense fallback={<Loading />}>
            <PlanetIdil />
            {children}
          </Suspense>
          <Footer />
        </div>
      </body>
    </html>
  )
}

function Loading() {
  return <h2>🌀 Loading...</h2>;
}